/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author CESAR DIAZ MARADIAGA
 */
public class PrincipalView extends javax.swing.JFrame {

	/**
	 * Creates new form PrincipalView
	 */
	public PrincipalView() {
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                mnUsuarios = new javax.swing.JPopupMenu();
                optEditarUsuario = new javax.swing.JMenuItem();
                optEliminarUsuario = new javax.swing.JMenuItem();
                mnEmpleados = new javax.swing.JPopupMenu();
                optEditarEmpleado = new javax.swing.JMenuItem();
                optEliminarEmpleado = new javax.swing.JMenuItem();
                mnMarcas = new javax.swing.JPopupMenu();
                optEditarMarca = new javax.swing.JMenuItem();
                mnProductos = new javax.swing.JPopupMenu();
                optEditarProducto = new javax.swing.JMenuItem();
                optEliminarProducto = new javax.swing.JMenuItem();
                jdEmpleadosUsuarios = new javax.swing.JDialog();
                jLabel24 = new javax.swing.JLabel();
                txtBuscarEmpleadoUsuario = new javax.swing.JTextField();
                jScrollPane2 = new javax.swing.JScrollPane();
                tblEmpleadosUsuario = new javax.swing.JTable();
                jDialog1 = new javax.swing.JDialog();
                pnlMenuLateral = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                lblUsuarioSistema = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                pnlOpcionInventario = new javax.swing.JPanel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jPanel5 = new javax.swing.JPanel();
                jLabel9 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                pnlOpcionEmpleados = new javax.swing.JPanel();
                jLabel11 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                pnlOpcionProveedores = new javax.swing.JPanel();
                jLabel13 = new javax.swing.JLabel();
                jLabel14 = new javax.swing.JLabel();
                pnlOpcionUsuario = new javax.swing.JPanel();
                jLabel16 = new javax.swing.JLabel();
                jLabel15 = new javax.swing.JLabel();
                jPanel9 = new javax.swing.JPanel();
                jLabel18 = new javax.swing.JLabel();
                jLabel17 = new javax.swing.JLabel();
                pnlVistaPrincipal = new javax.swing.JPanel();
                pnlUsuarios = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                jLabel19 = new javax.swing.JLabel();
                txtIdEmpleadoUsuario = new javax.swing.JTextField();
                txtEmpleadoUsuario = new javax.swing.JTextField();
                jLabel20 = new javax.swing.JLabel();
                txtNombreUsuario = new javax.swing.JTextField();
                txtPasswordUsuario = new javax.swing.JTextField();
                jLabel21 = new javax.swing.JLabel();
                cmbPermisoUsuario = new javax.swing.JComboBox<>();
                jLabel22 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblUsuarios = new javax.swing.JTable();
                jLabel23 = new javax.swing.JLabel();
                txtBuscarUsuario = new javax.swing.JTextField();
                btnLimpiarUsuario = new javax.swing.JButton();
                btnGuardarUsuario = new javax.swing.JButton();
                btnActualizarUsuario = new javax.swing.JButton();
                pnlInventario = new javax.swing.JPanel();
                jTabbedPane1 = new javax.swing.JTabbedPane();
                jPanel6 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                txtDescripcionProducto = new javax.swing.JTextField();
                jLabel29 = new javax.swing.JLabel();
                txtCodBarraProducto = new javax.swing.JTextField();
                jLabel30 = new javax.swing.JLabel();
                txtModeloProducto = new javax.swing.JTextField();
                jLabel31 = new javax.swing.JLabel();
                jsPrecioCostoProducto = new javax.swing.JSpinner();
                jLabel32 = new javax.swing.JLabel();
                jsPrecioVentaProducto = new javax.swing.JSpinner();
                jLabel33 = new javax.swing.JLabel();
                jLabel34 = new javax.swing.JLabel();
                jsCantidadProducto = new javax.swing.JSpinner();
                btnLimpiarProdducto = new javax.swing.JButton();
                btnGuardarProducto = new javax.swing.JButton();
                btnActualizarProducto = new javax.swing.JButton();
                jLabel35 = new javax.swing.JLabel();
                txtBuscarProducto = new javax.swing.JTextField();
                btnAgregarMarca = new javax.swing.JButton();
                jDesktopPane1 = new javax.swing.JDesktopPane();
                jifMarca = new javax.swing.JInternalFrame();
                jLabel36 = new javax.swing.JLabel();
                txtNombreMarca = new javax.swing.JTextField();
                btnGuardarMarca = new javax.swing.JButton();
                btnActualizarMarca = new javax.swing.JButton();
                jLabel37 = new javax.swing.JLabel();
                txtBuscarMarca = new javax.swing.JTextField();
                jScrollPane4 = new javax.swing.JScrollPane();
                tblMarcas = new javax.swing.JTable();
                jScrollPane5 = new javax.swing.JScrollPane();
                tblProductos = new javax.swing.JTable();
                cmbMarcasProducto = new javax.swing.JComboBox<>();
                jPanel7 = new javax.swing.JPanel();
                pnlEmpleados = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                jLabel25 = new javax.swing.JLabel();
                jLabel26 = new javax.swing.JLabel();
                txtNombresEmpleado = new javax.swing.JTextField();
                txtApellidosEmpleado = new javax.swing.JTextField();
                jLabel27 = new javax.swing.JLabel();
                txtTelefonoEmpleado = new javax.swing.JTextField();
                jScrollPane3 = new javax.swing.JScrollPane();
                tblEmpleados = new javax.swing.JTable();
                btnLimpiarEmpleado = new javax.swing.JButton();
                btnGuardarEmpleado = new javax.swing.JButton();
                btnActualizarEmpleado = new javax.swing.JButton();
                jLabel28 = new javax.swing.JLabel();
                txtBuscarEmpleado = new javax.swing.JTextField();

                optEditarUsuario.setText("Editar usuario");
                optEditarUsuario.setActionCommand("optEditarUsuario");
                mnUsuarios.add(optEditarUsuario);

                optEliminarUsuario.setText("Eliminar usuario");
                optEliminarUsuario.setActionCommand("optEliminarUsuario");
                mnUsuarios.add(optEliminarUsuario);

                optEditarEmpleado.setText("Editar empleado");
                optEditarEmpleado.setActionCommand("optEditarEmpleado");
                mnEmpleados.add(optEditarEmpleado);

                optEliminarEmpleado.setText("Eliminar empleado");
                optEliminarEmpleado.setActionCommand("optEliminarEmpleado");
                mnEmpleados.add(optEliminarEmpleado);

                optEditarMarca.setText("Editar marca");
                optEditarMarca.setActionCommand("optEditarMarca");
                mnMarcas.add(optEditarMarca);

                optEditarProducto.setText("Editar producto");
                optEditarProducto.setActionCommand("optEditarProducto");
                mnProductos.add(optEditarProducto);

                optEliminarProducto.setText("Eliminar producto");
                optEliminarProducto.setActionCommand("optEliminarProducto");
                mnProductos.add(optEliminarProducto);

                jdEmpleadosUsuarios.setTitle("Buscar empleado");

                jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel24.setText("Buscar por (Nombres,Apellidos,ID):");

                txtBuscarEmpleadoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                tblEmpleadosUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tblEmpleadosUsuario.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                tblEmpleadosUsuario.setRowHeight(24);
                jScrollPane2.setViewportView(tblEmpleadosUsuario);

                javax.swing.GroupLayout jdEmpleadosUsuariosLayout = new javax.swing.GroupLayout(jdEmpleadosUsuarios.getContentPane());
                jdEmpleadosUsuarios.getContentPane().setLayout(jdEmpleadosUsuariosLayout);
                jdEmpleadosUsuariosLayout.setHorizontalGroup(
                        jdEmpleadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jdEmpleadosUsuariosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jdEmpleadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel24)
                                        .addComponent(txtBuscarEmpleadoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE)
                );
                jdEmpleadosUsuariosLayout.setVerticalGroup(
                        jdEmpleadosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jdEmpleadosUsuariosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarEmpleadoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
                jDialog1.getContentPane().setLayout(jDialog1Layout);
                jDialog1Layout.setHorizontalGroup(
                        jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                );
                jDialog1Layout.setVerticalGroup(
                        jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
                );

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                pnlMenuLateral.setBackground(new java.awt.Color(0, 102, 204));

                jLabel1.setBackground(new java.awt.Color(102, 102, 255));
                jLabel1.setText("Icono");
                jLabel1.setOpaque(true);

                lblUsuarioSistema.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
                lblUsuarioSistema.setForeground(new java.awt.Color(255, 255, 255));
                lblUsuarioSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblUsuarioSistema.setText("Usuario");

                jPanel2.setBackground(new java.awt.Color(0, 102, 204));
                jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                jLabel3.setText("Icono");

                jLabel4.setBackground(new java.awt.Color(102, 153, 255));
                jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("Facturación");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                                .addContainerGap())
                );

                jPanel3.setBackground(new java.awt.Color(0, 102, 204));
                jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                jLabel5.setText("Icono");

                jLabel6.setBackground(new java.awt.Color(102, 153, 255));
                jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(255, 255, 255));
                jLabel6.setText("Reportes");

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                                .addContainerGap())
                );

                pnlOpcionInventario.setBackground(new java.awt.Color(0, 102, 204));
                pnlOpcionInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                jLabel7.setText("Icono");

                jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(255, 255, 255));
                jLabel8.setText("Inventario F3");

                javax.swing.GroupLayout pnlOpcionInventarioLayout = new javax.swing.GroupLayout(pnlOpcionInventario);
                pnlOpcionInventario.setLayout(pnlOpcionInventarioLayout);
                pnlOpcionInventarioLayout.setHorizontalGroup(
                        pnlOpcionInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlOpcionInventarioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                pnlOpcionInventarioLayout.setVerticalGroup(
                        pnlOpcionInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpcionInventarioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlOpcionInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                                .addContainerGap())
                );

                jPanel5.setBackground(new java.awt.Color(0, 102, 204));
                jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                jLabel9.setText("Icono");

                jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
                jLabel10.setForeground(new java.awt.Color(255, 255, 255));
                jLabel10.setText("Clientes y Cred.");

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel5Layout.setVerticalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                                .addContainerGap())
                );

                pnlOpcionEmpleados.setBackground(new java.awt.Color(0, 102, 204));
                pnlOpcionEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                jLabel11.setText("Icono");

                jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
                jLabel12.setForeground(new java.awt.Color(255, 255, 255));
                jLabel12.setText("Empleados F5");

                javax.swing.GroupLayout pnlOpcionEmpleadosLayout = new javax.swing.GroupLayout(pnlOpcionEmpleados);
                pnlOpcionEmpleados.setLayout(pnlOpcionEmpleadosLayout);
                pnlOpcionEmpleadosLayout.setHorizontalGroup(
                        pnlOpcionEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlOpcionEmpleadosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                pnlOpcionEmpleadosLayout.setVerticalGroup(
                        pnlOpcionEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpcionEmpleadosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlOpcionEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                                .addContainerGap())
                );

                pnlOpcionProveedores.setBackground(new java.awt.Color(0, 102, 204));
                pnlOpcionProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                jLabel13.setText("Icono");

                jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
                jLabel14.setForeground(new java.awt.Color(255, 255, 255));
                jLabel14.setText("Proveedores");

                javax.swing.GroupLayout pnlOpcionProveedoresLayout = new javax.swing.GroupLayout(pnlOpcionProveedores);
                pnlOpcionProveedores.setLayout(pnlOpcionProveedoresLayout);
                pnlOpcionProveedoresLayout.setHorizontalGroup(
                        pnlOpcionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlOpcionProveedoresLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                pnlOpcionProveedoresLayout.setVerticalGroup(
                        pnlOpcionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpcionProveedoresLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlOpcionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                                .addContainerGap())
                );

                pnlOpcionUsuario.setBackground(new java.awt.Color(0, 102, 204));
                pnlOpcionUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
                jLabel16.setForeground(new java.awt.Color(255, 255, 255));
                jLabel16.setText("Usuarios");

                jLabel15.setText("Icono");

                javax.swing.GroupLayout pnlOpcionUsuarioLayout = new javax.swing.GroupLayout(pnlOpcionUsuario);
                pnlOpcionUsuario.setLayout(pnlOpcionUsuarioLayout);
                pnlOpcionUsuarioLayout.setHorizontalGroup(
                        pnlOpcionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlOpcionUsuarioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                pnlOpcionUsuarioLayout.setVerticalGroup(
                        pnlOpcionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpcionUsuarioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlOpcionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                                .addContainerGap())
                );

                jPanel9.setBackground(new java.awt.Color(0, 102, 204));
                jPanel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                jLabel18.setText("Icono");

                jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
                jLabel17.setForeground(new java.awt.Color(255, 255, 255));
                jLabel17.setText("Opcion8");

                javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
                jPanel9.setLayout(jPanel9Layout);
                jPanel9Layout.setHorizontalGroup(
                        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel9Layout.setVerticalGroup(
                        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                                .addContainerGap())
                );

                javax.swing.GroupLayout pnlMenuLateralLayout = new javax.swing.GroupLayout(pnlMenuLateral);
                pnlMenuLateral.setLayout(pnlMenuLateralLayout);
                pnlMenuLateralLayout.setHorizontalGroup(
                        pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlMenuLateralLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnlOpcionInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnlOpcionEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnlOpcionProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnlOpcionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pnlMenuLateralLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(lblUsuarioSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                pnlMenuLateralLayout.setVerticalGroup(
                        pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlMenuLateralLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(lblUsuarioSistema)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlOpcionInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlOpcionEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlOpcionProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlOpcionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pnlVistaPrincipal.setLayout(new java.awt.CardLayout());

                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 15))); // NOI18N

                jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel19.setText("Empleado:");

                txtIdEmpleadoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                txtIdEmpleadoUsuario.setEnabled(false);

                txtEmpleadoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                txtEmpleadoUsuario.setEnabled(false);

                jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel20.setText("Usuario:");

                txtNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                txtPasswordUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel21.setText("Permiso:");

                cmbPermisoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                cmbPermisoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Contabilidad", "Inventario", "Ventas" }));

                jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel22.setText("Contraseña:");

                tblUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                tblUsuarios.setComponentPopupMenu(mnUsuarios);
                tblUsuarios.setOpaque(false);
                tblUsuarios.setRowHeight(24);
                tblUsuarios.setShowGrid(true);
                jScrollPane1.setViewportView(tblUsuarios);

                jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel23.setText("Buscar por (Empleado,Usuario):");

                txtBuscarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                btnLimpiarUsuario.setBackground(new java.awt.Color(102, 102, 255));
                btnLimpiarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                btnLimpiarUsuario.setForeground(new java.awt.Color(255, 255, 255));
                btnLimpiarUsuario.setText("Limpiar");
                btnLimpiarUsuario.setActionCommand("btnLimpiarUsuario");

                btnGuardarUsuario.setBackground(new java.awt.Color(102, 102, 255));
                btnGuardarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                btnGuardarUsuario.setForeground(new java.awt.Color(255, 255, 255));
                btnGuardarUsuario.setText("Guardar");
                btnGuardarUsuario.setActionCommand("btnGuardarUsuario");

                btnActualizarUsuario.setBackground(new java.awt.Color(102, 102, 255));
                btnActualizarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                btnActualizarUsuario.setForeground(new java.awt.Color(255, 255, 255));
                btnActualizarUsuario.setText("Actualizar");
                btnActualizarUsuario.setActionCommand("btnActualizarUsuario");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(225, 225, 225)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel21)
                                                        .addComponent(jLabel19)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(txtIdEmpleadoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtEmpleadoUsuario))
                                                        .addComponent(cmbPermisoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(btnLimpiarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnGuardarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnActualizarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtNombreUsuario)
                                                                        .addComponent(jLabel20))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel22)
                                                                        .addComponent(txtPasswordUsuario)))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel23))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(txtBuscarUsuario)
                                                .addGap(344, 344, 344)))
                                .addGap(225, 225, 225))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtIdEmpleadoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEmpleadoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbPermisoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnLimpiarUsuario)
                                        .addComponent(btnGuardarUsuario)
                                        .addComponent(btnActualizarUsuario))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23)
                                .addGap(3, 3, 3)
                                .addComponent(txtBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout pnlUsuariosLayout = new javax.swing.GroupLayout(pnlUsuarios);
                pnlUsuarios.setLayout(pnlUsuariosLayout);
                pnlUsuariosLayout.setHorizontalGroup(
                        pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuariosLayout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(137, 137, 137))
                );
                pnlUsuariosLayout.setVerticalGroup(
                        pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlUsuariosLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(31, 31, 31))
                );

                pnlVistaPrincipal.add(pnlUsuarios, "card2");

                jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel2.setText("Descripciòn:");

                txtDescripcionProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel29.setText("Codigo de barra:");

                txtCodBarraProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel30.setText("Modelo:");

                txtModeloProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel31.setText("Precio costo:");

                jsPrecioCostoProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jsPrecioCostoProducto.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.01f));

                jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel32.setText("Precio venta:");

                jsPrecioVentaProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jsPrecioVentaProducto.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.01f));

                jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel33.setText("Marca:");

                jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel34.setText("Cantidad:");

                jsCantidadProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jsCantidadProducto.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.01f));

                btnLimpiarProdducto.setBackground(new java.awt.Color(0, 102, 255));
                btnLimpiarProdducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                btnLimpiarProdducto.setForeground(new java.awt.Color(255, 255, 255));
                btnLimpiarProdducto.setText("Limpiar");
                btnLimpiarProdducto.setActionCommand("btnLimpiarProducto");

                btnGuardarProducto.setBackground(new java.awt.Color(0, 102, 255));
                btnGuardarProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                btnGuardarProducto.setForeground(new java.awt.Color(255, 255, 255));
                btnGuardarProducto.setText("Guardar");
                btnGuardarProducto.setActionCommand("btnGuardarProducto");

                btnActualizarProducto.setBackground(new java.awt.Color(0, 102, 255));
                btnActualizarProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                btnActualizarProducto.setForeground(new java.awt.Color(255, 255, 255));
                btnActualizarProducto.setText("Actualizar");
                btnActualizarProducto.setActionCommand("btnActualizarProducto");

                jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel35.setText("Buscar por(cod.barra,descripción,marca):");

                txtBuscarProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                btnAgregarMarca.setBackground(new java.awt.Color(0, 102, 255));
                btnAgregarMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                btnAgregarMarca.setForeground(new java.awt.Color(255, 255, 255));
                btnAgregarMarca.setText("+ Marca");
                btnAgregarMarca.setActionCommand("btnAgregarMarca");

                jifMarca.setClosable(true);
                jifMarca.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
                jifMarca.setTitle("Gestiòn de marcas");
                jifMarca.setVisible(true);

                jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel36.setText("Nombre:");

                txtNombreMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                btnGuardarMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                btnGuardarMarca.setText("Guardar");
                btnGuardarMarca.setActionCommand("btnGuardarMarca");

                btnActualizarMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                btnActualizarMarca.setText("Actualizar");
                btnActualizarMarca.setActionCommand("btnActualizarMarca");

                jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel37.setText("Buscar:");

                txtBuscarMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                tblMarcas.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                tblMarcas.setComponentPopupMenu(mnMarcas);
                tblMarcas.setFocusable(false);
                tblMarcas.setShowGrid(true);
                jScrollPane4.setViewportView(tblMarcas);

                javax.swing.GroupLayout jifMarcaLayout = new javax.swing.GroupLayout(jifMarca.getContentPane());
                jifMarca.getContentPane().setLayout(jifMarcaLayout);
                jifMarcaLayout.setHorizontalGroup(
                        jifMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jifMarcaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jifMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jifMarcaLayout.createSequentialGroup()
                                                .addComponent(jLabel36)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifMarcaLayout.createSequentialGroup()
                                                .addGroup(jifMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jifMarcaLayout.createSequentialGroup()
                                                                .addComponent(jLabel37)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtBuscarMarca))
                                                        .addComponent(txtNombreMarca))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnGuardarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnActualizarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                        .addComponent(jScrollPane4)
                );
                jifMarcaLayout.setVerticalGroup(
                        jifMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jifMarcaLayout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jifMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNombreMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnGuardarMarca)
                                        .addComponent(btnActualizarMarca))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jifMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel37)
                                        .addComponent(txtBuscarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                );

                jDesktopPane1.setLayer(jifMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);

                javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
                jDesktopPane1.setLayout(jDesktopPane1Layout);
                jDesktopPane1Layout.setHorizontalGroup(
                        jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jifMarca))
                );
                jDesktopPane1Layout.setVerticalGroup(
                        jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jifMarca)
                                .addContainerGap())
                );

                tblProductos.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                tblProductos.setComponentPopupMenu(mnProductos);
                tblProductos.setFocusable(false);
                tblProductos.setRowHeight(24);
                tblProductos.setShowGrid(true);
                jScrollPane5.setViewportView(tblProductos);

                cmbMarcasProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                cmbMarcasProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(txtDescripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel29)
                                                                        .addComponent(txtCodBarraProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jLabel35)
                                                        .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jLabel33)
                                                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                                                .addComponent(btnLimpiarProdducto)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(btnGuardarProducto)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(btnActualizarProducto)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(btnAgregarMarca))
                                                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(txtModeloProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jsPrecioCostoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jLabel31)))
                                                                        .addComponent(cmbMarcasProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jsPrecioVentaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel32)
                                                                        .addComponent(jLabel34)
                                                                        .addComponent(jsCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(18, 18, 18)
                                                .addComponent(jDesktopPane1)))
                                .addContainerGap())
                );
                jPanel6Layout.setVerticalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtDescripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                                                                .addComponent(jLabel30)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(txtModeloProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                        .addComponent(jLabel31)
                                                                                        .addComponent(jLabel32))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                        .addComponent(jsPrecioCostoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jsPrecioVentaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                                                .addComponent(jLabel33)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                        .addComponent(cmbMarcasProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jsCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(10, 10, 10))
                                                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                                                .addComponent(jLabel34)
                                                                                .addGap(44, 44, 44)))
                                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(btnLimpiarProdducto)
                                                                        .addComponent(btnGuardarProducto)
                                                                        .addComponent(btnActualizarProducto)
                                                                        .addComponent(btnAgregarMarca)))
                                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addComponent(jLabel29)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtCodBarraProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel35)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                .addContainerGap())
                );

                jTabbedPane1.addTab("Gestiòn de productos", jPanel6);

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1086, Short.MAX_VALUE)
                );
                jPanel7Layout.setVerticalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 531, Short.MAX_VALUE)
                );

                jTabbedPane1.addTab("Gestión de pedidos", jPanel7);

                javax.swing.GroupLayout pnlInventarioLayout = new javax.swing.GroupLayout(pnlInventario);
                pnlInventario.setLayout(pnlInventarioLayout);
                pnlInventarioLayout.setHorizontalGroup(
                        pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlInventarioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1)
                                .addContainerGap())
                );
                pnlInventarioLayout.setVerticalGroup(
                        pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlInventarioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1)
                                .addContainerGap())
                );

                pnlVistaPrincipal.add(pnlInventario, "card3");

                jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingreso de empleados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 15))); // NOI18N

                jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel25.setText("Nombres:");

                jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel26.setText("Apellidos:");

                txtNombresEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                txtApellidosEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel27.setText("Telefono:");

                txtTelefonoEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                tblEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                tblEmpleados.setComponentPopupMenu(mnEmpleados);
                jScrollPane3.setViewportView(tblEmpleados);

                btnLimpiarEmpleado.setBackground(new java.awt.Color(51, 102, 255));
                btnLimpiarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                btnLimpiarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
                btnLimpiarEmpleado.setText("Limpiar");
                btnLimpiarEmpleado.setActionCommand("btnLimpiarEmpleado");

                btnGuardarEmpleado.setBackground(new java.awt.Color(51, 102, 255));
                btnGuardarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                btnGuardarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
                btnGuardarEmpleado.setText("Guardar");
                btnGuardarEmpleado.setActionCommand("btnGuardarEmpleado");

                btnActualizarEmpleado.setBackground(new java.awt.Color(51, 102, 255));
                btnActualizarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                btnActualizarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
                btnActualizarEmpleado.setText("Actualizar");
                btnActualizarEmpleado.setActionCommand("btnActualizarEmpleado");

                jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel28.setText("Buscar por (Nombres,Apellidos):");

                txtBuscarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addComponent(btnLimpiarEmpleado)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnGuardarEmpleado)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnActualizarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                                                        .addComponent(jLabel28)
                                                        .addComponent(txtBuscarEmpleado)
                                                        .addComponent(jLabel25)
                                                        .addComponent(jLabel26)
                                                        .addComponent(txtNombresEmpleado)
                                                        .addComponent(txtApellidosEmpleado)
                                                        .addComponent(jLabel27)
                                                        .addComponent(txtTelefonoEmpleado))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombresEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApellidosEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnLimpiarEmpleado)
                                        .addComponent(btnGuardarEmpleado)
                                        .addComponent(btnActualizarEmpleado))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28)
                                .addGap(3, 3, 3)
                                .addComponent(txtBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                .addContainerGap())
                );

                javax.swing.GroupLayout pnlEmpleadosLayout = new javax.swing.GroupLayout(pnlEmpleados);
                pnlEmpleados.setLayout(pnlEmpleadosLayout);
                pnlEmpleadosLayout.setHorizontalGroup(
                        pnlEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlEmpleadosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                pnlEmpleadosLayout.setVerticalGroup(
                        pnlEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlEmpleadosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12))
                );

                pnlVistaPrincipal.add(pnlEmpleados, "card4");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlMenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlVistaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlMenuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlVistaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PrincipalView().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        public javax.swing.JButton btnActualizarEmpleado;
        public javax.swing.JButton btnActualizarMarca;
        public javax.swing.JButton btnActualizarProducto;
        public javax.swing.JButton btnActualizarUsuario;
        public javax.swing.JButton btnAgregarMarca;
        public javax.swing.JButton btnGuardarEmpleado;
        public javax.swing.JButton btnGuardarMarca;
        public javax.swing.JButton btnGuardarProducto;
        public javax.swing.JButton btnGuardarUsuario;
        public javax.swing.JButton btnLimpiarEmpleado;
        public javax.swing.JButton btnLimpiarProdducto;
        public javax.swing.JButton btnLimpiarUsuario;
        public javax.swing.JComboBox<String> cmbMarcasProducto;
        public javax.swing.JComboBox<String> cmbPermisoUsuario;
        private javax.swing.JDesktopPane jDesktopPane1;
        private javax.swing.JDialog jDialog1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel19;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel20;
        private javax.swing.JLabel jLabel21;
        private javax.swing.JLabel jLabel22;
        private javax.swing.JLabel jLabel23;
        private javax.swing.JLabel jLabel24;
        private javax.swing.JLabel jLabel25;
        private javax.swing.JLabel jLabel26;
        private javax.swing.JLabel jLabel27;
        private javax.swing.JLabel jLabel28;
        private javax.swing.JLabel jLabel29;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel30;
        private javax.swing.JLabel jLabel31;
        private javax.swing.JLabel jLabel32;
        private javax.swing.JLabel jLabel33;
        private javax.swing.JLabel jLabel34;
        private javax.swing.JLabel jLabel35;
        private javax.swing.JLabel jLabel36;
        private javax.swing.JLabel jLabel37;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        public javax.swing.JPanel jPanel2;
        public javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        public javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel7;
        public javax.swing.JPanel jPanel9;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JScrollPane jScrollPane5;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JTabbedPane jTabbedPane1;
        public javax.swing.JDialog jdEmpleadosUsuarios;
        public javax.swing.JInternalFrame jifMarca;
        public javax.swing.JSpinner jsCantidadProducto;
        public javax.swing.JSpinner jsPrecioCostoProducto;
        public javax.swing.JSpinner jsPrecioVentaProducto;
        public javax.swing.JLabel lblUsuarioSistema;
        private javax.swing.JPopupMenu mnEmpleados;
        private javax.swing.JPopupMenu mnMarcas;
        private javax.swing.JPopupMenu mnProductos;
        private javax.swing.JPopupMenu mnUsuarios;
        public javax.swing.JMenuItem optEditarEmpleado;
        public javax.swing.JMenuItem optEditarMarca;
        public javax.swing.JMenuItem optEditarProducto;
        public javax.swing.JMenuItem optEditarUsuario;
        public javax.swing.JMenuItem optEliminarEmpleado;
        public javax.swing.JMenuItem optEliminarProducto;
        public javax.swing.JMenuItem optEliminarUsuario;
        public javax.swing.JPanel pnlEmpleados;
        public javax.swing.JPanel pnlInventario;
        private javax.swing.JPanel pnlMenuLateral;
        public javax.swing.JPanel pnlOpcionEmpleados;
        public javax.swing.JPanel pnlOpcionInventario;
        public javax.swing.JPanel pnlOpcionProveedores;
        public javax.swing.JPanel pnlOpcionUsuario;
        public javax.swing.JPanel pnlUsuarios;
        private javax.swing.JPanel pnlVistaPrincipal;
        public javax.swing.JTable tblEmpleados;
        public javax.swing.JTable tblEmpleadosUsuario;
        public javax.swing.JTable tblMarcas;
        public javax.swing.JTable tblProductos;
        public javax.swing.JTable tblUsuarios;
        public javax.swing.JTextField txtApellidosEmpleado;
        public javax.swing.JTextField txtBuscarEmpleado;
        public javax.swing.JTextField txtBuscarEmpleadoUsuario;
        public javax.swing.JTextField txtBuscarMarca;
        public javax.swing.JTextField txtBuscarProducto;
        public javax.swing.JTextField txtBuscarUsuario;
        public javax.swing.JTextField txtCodBarraProducto;
        public javax.swing.JTextField txtDescripcionProducto;
        public javax.swing.JTextField txtEmpleadoUsuario;
        public javax.swing.JTextField txtIdEmpleadoUsuario;
        public javax.swing.JTextField txtModeloProducto;
        public javax.swing.JTextField txtNombreMarca;
        public javax.swing.JTextField txtNombreUsuario;
        public javax.swing.JTextField txtNombresEmpleado;
        public javax.swing.JTextField txtPasswordUsuario;
        public javax.swing.JTextField txtTelefonoEmpleado;
        // End of variables declaration//GEN-END:variables
}
